#!/usr/bin/env python3
"""Build PNG summary figures for the LaTeX report (TF--IDF gaps, LLM audit counts).

Reads existing CSVs under ../results/. Run from repo root or report/:
  python report/gen_report_figures.py

LLM audits: writes ``results/report_figures/llm_audit_pair_bars.png`` (side-by-side,
used in ``main.tex``) plus standalone same-string / hierarchical PNGs.
"""
from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORT_DIR = Path(__file__).resolve().parent
OUT_DIR = ROOT / "results" / "report_figures"
TFIDF_CSV = ROOT / "results" / "tfidf" / "shared_terms_mean_tfidf_gap.csv"
LLM_PER_CASE = ROOT / "results" / "llm_align" / "llm_pair_review_per_case.csv"
LLM_HIER_PER_CASE = ROOT / "results" / "llm_align" / "llm_pair_review_per_case_hierarchical.csv"
GENERATED_HIER_TEX = REPORT_DIR / "_generated_llm_hier.tex"


def _llm_decision_counts(path: Path) -> tuple[int, int, int, int]:
    """Return (n, keep, substitute, incomparable) from a review CSV."""
    if not path.is_file():
        return 0, 0, 0, 0
    c: Counter[str] = Counter()
    with path.open(encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            k = (r.get("llm_decision") or "").strip().upper()
            if k:
                c[k] += 1
    n = sum(c.values())
    return n, c.get("KEEP", 0), c.get("SUBSTITUTE", 0), c.get("INCOMPARABLE", 0)


def _bar_ylim_and_labels(counts: list[int]) -> float:
    """Upper y-axis limit with room for value labels above the tallest bar."""
    m = max(counts) if counts else 0
    if m <= 0:
        return 12.0
    # Extra headroom so bar_label (points above bars) stays clear of the title.
    return float(m) * 1.42 + 12.0


def _style_llm_axis(ax, ymax: float) -> None:
    ax.set_ylim(0.0, ymax)
    ax.margins(x=0.06)
    ax.yaxis.grid(True, linestyle="--", alpha=0.28, linewidth=0.8)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


def _write_hier_tex(n: int, keep: int, sub: int, inc: int) -> None:
    lines = [
        "% Auto-generated by report/gen_report_figures.py — do not edit.",
        "% Rebuild: python3 report/gen_report_figures.py",
        r"\def\LLMHierN{" + str(n) + "}",
        r"\def\LLMHierKeep{" + str(keep) + "}",
        r"\def\LLMHierSub{" + str(sub) + "}",
        r"\def\LLMHierInc{" + str(inc) + "}",
        "",
    ]
    GENERATED_HIER_TEX.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", GENERATED_HIER_TEX)


def main() -> None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as e:
        raise SystemExit(
            "matplotlib is required: pip install matplotlib\n" + str(e)
        ) from e

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # --- TF-IDF: top gaps A vs B ---
    rows: list[tuple[str, float]] = []
    with TFIDF_CSV.open(encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            term = (r.get("term") or "").strip()
            if not term:
                continue
            try:
                d = float(r["difference_a_minus_b"])
            except (KeyError, ValueError):
                continue
            rows.append((term, d))
    rows.sort(key=lambda x: x[1], reverse=True)
    top_a = rows[:10]
    bottom = sorted(rows, key=lambda x: x[1])[:10]
    top_b = [(t, -d) for t, d in bottom]

    fig, axes = plt.subplots(1, 2, figsize=(9.5, 4.2), dpi=150)
    terms_a, vals_a = zip(*top_a) if top_a else ([], [])
    axes[0].barh(list(terms_a)[::-1], list(vals_a)[::-1], color="#2c5282")
    axes[0].set_xlabel("Mean TF–IDF gap (A − B)")
    axes[0].set_title("Higher in human (A)")
    terms_b, vals_b = zip(*top_b) if top_b else ([], [])
    axes[1].barh(list(terms_b)[::-1], list(vals_b)[::-1], color="#744210")
    axes[1].set_xlabel("Mean TF–IDF gap (B − A)")
    axes[1].set_title("Higher in model (B)")
    fig.suptitle("Largest mean TF–IDF gaps on shared lemmas (117 strict pairs)", fontsize=11)
    fig.tight_layout()
    p_tfidf = OUT_DIR / "tfidf_gap_bars.png"
    fig.savefig(p_tfidf, bbox_inches="tight")
    plt.close(fig)
    print("Wrote", p_tfidf)

    # --- LLM audit bar charts: one side-by-side figure (LaTeX includes single asset) ---
    labels = ["KEEP", "SUBSTITUTE", "INCOMPARABLE"]
    colors = ["#276749", "#c05621", "#718096"]

    n_ss, k_ss, s_ss, i_ss = _llm_decision_counts(LLM_PER_CASE)
    counts_ss = [k_ss, s_ss, i_ss] if n_ss else [44, 2, 2]
    n_ss_label = n_ss if n_ss else 48

    n_h, k_h, s_h, i_h = _llm_decision_counts(LLM_HIER_PER_CASE)
    _write_hier_tex(n_h, k_h, s_h, i_h)
    counts_h = [k_h, s_h, i_h] if n_h else [0, 0, 0]

    fig_pair, axes_pair = plt.subplots(
        1,
        2,
        figsize=(10.0, 3.95),
        dpi=150,
        gridspec_kw={"wspace": 0.26},
    )

    def _panel_title(base: str, n_rows: int) -> str:
        if n_rows:
            return f"{base} (n = {n_rows})"
        return f"{base} (no CSV)"

    for idx, (ax, counts, n_rows, title) in enumerate(
        (
            (
                axes_pair[0],
                counts_ss,
                n_ss_label,
                "Same-string overlap audit",
            ),
            (
                axes_pair[1],
                counts_h,
                n_h,
                "Hierarchical is-a seed audit",
            ),
        )
    ):
        ymax = _bar_ylim_and_labels(counts)
        bars = ax.bar(
            labels,
            counts,
            color=colors,
            width=0.62,
            edgecolor="white",
            linewidth=0.75,
        )
        _style_llm_axis(ax, ymax)
        ax.bar_label(
            bars,
            labels=[str(int(c)) for c in counts],
            fontsize=10,
            fontweight="medium",
            padding=12,
        )
        if idx == 0:
            ax.set_ylabel("Row count")
        ax.set_title(_panel_title(title, n_rows), fontsize=10.5, pad=22)
    fig_pair.subplots_adjust(left=0.09, right=0.98, top=0.78, bottom=0.15)
    p_pair = OUT_DIR / "llm_audit_pair_bars.png"
    fig_pair.savefig(p_pair, bbox_inches="tight", pad_inches=0.22)
    plt.close(fig_pair)
    print("Wrote", p_pair)

    # Standalone copies (same styling) for slides or external reuse
    def _one_llm_png(counts: list[int], n_rows: int, base_title: str, out: Path) -> None:
        fig, ax = plt.subplots(figsize=(5.15, 3.95), dpi=150)
        ymax = _bar_ylim_and_labels(counts)
        bars = ax.bar(
            labels,
            counts,
            color=colors,
            width=0.62,
            edgecolor="white",
            linewidth=0.75,
        )
        _style_llm_axis(ax, ymax)
        ax.bar_label(
            bars,
            labels=[str(int(c)) for c in counts],
            fontsize=10,
            fontweight="medium",
            padding=12,
        )
        ax.set_ylabel("Row count")
        ax.set_title(_panel_title(base_title, n_rows), fontsize=10.5, pad=22)
        fig.subplots_adjust(left=0.14, right=0.96, top=0.78, bottom=0.15)
        fig.savefig(out, bbox_inches="tight", pad_inches=0.22)
        plt.close(fig)

    p_llm = OUT_DIR / "llm_same_string_audit_bars.png"
    _one_llm_png(counts_ss, n_ss_label, "Same-string overlap audit", p_llm)
    print("Wrote", p_llm)
    p_hier = OUT_DIR / "llm_hierarchical_audit_bars.png"
    _one_llm_png(counts_h, n_h, "Hierarchical is-a seed audit", p_hier)
    print("Wrote", p_hier)


if __name__ == "__main__":
    main()
